### ISSUE TITLE
Make the catkin version master and rosbuild version to another branch

### ISSUE THREAD

**Issue by versatran01** [KumarRobotics/vicon#4]
This will break someone's stuff.

Changes are:
1. all messages are under `vicon` namespace, e.g. the `ViconSubject` message of QuadrotorBravo is now `/vicon/QuadrotorBravo` instead of just `/QuadrotorBravo`.
2. `Odometry` message are under `vicon/model` namespace, e.g. the `nav_msgs/Odometry` message of QuadrotorBravo is now `/vicon/QuadrotorBravo/odom` instead of `/QuadrotorBravo_odom`.
3. all vicon odometry message have proper `frame_id` and `child_frame_id`, e.g. the `nav_msgs/Odometry` message header of QuadrotorBravo will have `header.frame_id = vicon` and `header.child_frame_id = /QuadrotorBravo/base_link`.
4. Option to publish a tf message.
5. catkin package instead of rosbuild package.

**Comment by versatran01** [comment]
Is this going to happen?

**Comment by kartikmohta** [comment]
I hope so :)
